/**
 *
 * Copyright 2008 (C) The original author or authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.papoose.core;

import org.osgi.service.startlevel.StartLevel;
import org.osgi.framework.Bundle;

/**
 * @version $Revision$ $Date$
 */
public class StartLevelImpl implements StartLevel
{
    public int getStartLevel()
    {
        return 0;  //todo: consider this autogenerated code
    }

    public void setStartLevel(int i)
    {
        //todo: consider this autogenerated code
    }

    public int getBundleStartLevel(Bundle bundle)
    {
        return 0;  //todo: consider this autogenerated code
    }

    public void setBundleStartLevel(Bundle bundle, int i)
    {
        //todo: consider this autogenerated code
    }

    public int getInitialBundleStartLevel()
    {
        return 0;  //todo: consider this autogenerated code
    }

    public void setInitialBundleStartLevel(int i)
    {
        //todo: consider this autogenerated code
    }

    public boolean isBundlePersistentlyStarted(Bundle bundle)
    {
        return false;  //todo: consider this autogenerated code
    }

    public boolean isBundleActivationPolicyUsed(Bundle bundle)
    {
        return false;  //todo: consider this autogenerated code
    }
}
