/**
 *
 * Copyright 2007 (C) The original author or authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.papoose.core.framework;

import java.io.File;
import java.io.InputStream;
import java.net.URL;
import java.util.Collections;
import java.util.Properties;
import java.util.TreeSet;
import java.util.List;

import junit.framework.TestCase;

import org.papoose.core.framework.spi.BundleStore;
import org.papoose.core.framework.spi.Store;
import org.papoose.core.framework.spi.ThreadPool;
import org.papoose.core.framework.ArchiveStore;

import org.osgi.framework.BundleException;


/**
 * @version $Revision$ $Date$
 */
public class BundleClassLoaderTest extends TestCase
{
    public void testLoad()
    {
        Papoose papoose = new Papoose(
                new Store()
                {
                    public List<BundleStore> loadBundleStores() throws BundleException
                    {
                        return null;  //todo: consider this autogenerated code
                    }

                    public BundleStore allocateBundleStore(long bundleId, String location) throws BundleException
                    {
                        return null;  //todo: consider this autogenerated code
                    }

                    public BundleStore loadBundleStore(long bundleId) throws BundleException
                    {
                        return null;  //todo: consider this autogenerated code
                    }

                    public void removeBundleStore(long bundleId) throws BundleException
                    {
                        //todo: consider this autogenerated code
                    }

                    public ArchiveStore allocateArchiveStore(Papoose framework, long bundleId, int generaton, InputStream inputStream) throws BundleException
                    {
                        return null;  //todo: consider this autogenerated code
                    }

                    public List<ArchiveStore> loadArchiveStores(Papoose framework, long bundleId) throws BundleException
                    {
                        return null;  //todo: consider this autogenerated code
                    }

                    public void removeArchiveStore(long bundleId, int generation) throws BundleException
                    {
                        //todo: consider this autogenerated code
                    }
                },
                new ThreadPool()
                {
                    public boolean runInThread(Runnable runnable)
                    {
                        return false;  //todo: consider this autogenerated code
                    }
                },
                new Properties());

        String[] bootDelegates = new String[]{"com.foo.bar.", "com.bar"};
        BundleClassLoader bundleClassLoader = new BundleClassLoader("bundle.1241", new URL[]{}, Thread.currentThread().getContextClassLoader(),
                                                                    bootDelegates,
                                                                    new Wire[]{},
                                                                    new URL[]{},
                                                                    new String[]{},
                                                                    Collections.EMPTY_SET,
                                                                    papoose,
                                                                    new TreeSet());
        bundleClassLoader.setWires(Collections.<Wire>emptySet());

        try
        {
            Class test = bundleClassLoader.loadClass("com.foo.bar.Car");
        }
        catch (ClassNotFoundException e)
        {
            e.printStackTrace();  //todo: consider this autogenerated code
        }
    }
}
