/**
 *
 * Copyright 2008 (C) The original author or authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.papoose.core.framework.mock;

import java.io.File;

import org.osgi.framework.BundleException;

import org.papoose.core.framework.spi.BundleStore;

/**
 * @version $Revision$ $Date$
 */
public class MockBundleStore implements BundleStore
{
    private final long bundleId;
    private final String location;

    public MockBundleStore(long bundleId, String location)
    {
        this.bundleId = bundleId;
        this.location = location;
    }

    public long getBundleId()
    {
        return bundleId;
    }

    public String getLocation()
    {
        return location;
    }

    public File getDataRoot()
    {
        return null;  //todo: consider this autogenerated code
    }

    public boolean isStarted() throws BundleException
    {
        return false;  //todo: consider this autogenerated code
    }

    public void setStarted(boolean started) throws BundleException
    {
        int i = 0;
        //todo: consider this autogenerated code
    }

    public long getLastModified() throws BundleException
    {
        return 0;  //todo: consider this autogenerated code
    }

    public void updateLastModified() throws BundleException
    {
        int i = 0;
        //todo: consider this autogenerated code
    }
}
