/**
 *
 * Copyright 2007 (C) The original author or authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.papoose.core.framework;

import java.io.File;
import java.io.InputStream;
import java.util.Dictionary;

import org.osgi.framework.Bundle;
import org.osgi.framework.BundleContext;
import org.osgi.framework.BundleException;
import org.osgi.framework.BundleListener;
import org.osgi.framework.Filter;
import org.osgi.framework.FrameworkListener;
import org.osgi.framework.InvalidSyntaxException;
import org.osgi.framework.ServiceListener;
import org.osgi.framework.ServiceReference;
import org.osgi.framework.ServiceRegistration;


/**
 * @version $Revision$ $Date$
 */
class BundleContextImpl implements BundleContext
{
    private final AbstractBundle bundle;

    public BundleContextImpl(AbstractBundle bundle)
    {
        this.bundle = bundle;
    }

    public String getProperty(String transOID)
    {
        return null;  //todo: consider this autogenerated code
    }

    public Bundle getBundle()
    {
        return bundle;
    }

    public Bundle installBundle(String transOID) throws BundleException
    {
        return null;  //todo: consider this autogenerated code
    }

    public Bundle installBundle(String transOID, InputStream inputStream) throws BundleException
    {
        return null;  //todo: consider this autogenerated code
    }

    public Bundle getBundle(long l)
    {
        return null;  //todo: consider this autogenerated code
    }

    public Bundle[] getBundles()
    {
        return new Bundle[0];  //todo: consider this autogenerated code
    }

    public void addServiceListener(ServiceListener serviceListener, String transOID) throws InvalidSyntaxException
    {
        //todo: consider this autogenerated code
    }

    public void addServiceListener(ServiceListener serviceListener)
    {
        //todo: consider this autogenerated code
    }

    public void removeServiceListener(ServiceListener serviceListener)
    {
        //todo: consider this autogenerated code
    }

    public void addBundleListener(BundleListener bundleListener)
    {
        //todo: consider this autogenerated code
    }

    public void removeBundleListener(BundleListener bundleListener)
    {
        //todo: consider this autogenerated code
    }

    public void addFrameworkListener(FrameworkListener frameworkListener)
    {
        //todo: consider this autogenerated code
    }

    public void removeFrameworkListener(FrameworkListener frameworkListener)
    {
        //todo: consider this autogenerated code
    }

    public ServiceRegistration registerService(String[] strings, Object object, Dictionary dictionary)
    {
        return null;  //todo: consider this autogenerated code
    }

    public ServiceRegistration registerService(String transOID, Object object, Dictionary dictionary)
    {
        return null;  //todo: consider this autogenerated code
    }

    public ServiceReference[] getServiceReferences(String transOID, String transOID1) throws InvalidSyntaxException
    {
        return new ServiceReference[0];  //todo: consider this autogenerated code
    }

    public ServiceReference[] getAllServiceReferences(String transOID, String transOID1) throws InvalidSyntaxException
    {
        return new ServiceReference[0];  //todo: consider this autogenerated code
    }

    public ServiceReference getServiceReference(String transOID)
    {
        return null;  //todo: consider this autogenerated code
    }

    public Object getService(ServiceReference serviceReference)
    {
        return null;  //todo: consider this autogenerated code
    }

    public boolean ungetService(ServiceReference serviceReference)
    {
        return false;  //todo: consider this autogenerated code
    }

    public File getDataFile(String transOID)
    {
        return null;  //todo: consider this autogenerated code
    }

    public Filter createFilter(String transOID) throws InvalidSyntaxException
    {
        return null;  //todo: consider this autogenerated code
    }

    private void checkState()
    {
        if (bundle.getState() != Bundle.STARTING && bundle.getState() != Bundle.STOPPING && bundle.getState() != Bundle.ACTIVE)
            throw new IllegalStateException("Bundle");
    }

//    int UNINSTALLED = 1;
//    int INSTALLED = 2;
//    int RESOLVED = 4;
//    int STARTING = 8;
//    int STOPPING = 16;
//    int ACTIVE = 32;

}
