/**
 *
 * Copyright 2007 (C) The original author or authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.papoose.core.framework;

import java.util.Dictionary;
import java.util.Enumeration;
import java.io.InputStream;
import java.io.IOException;
import java.net.URL;

import org.osgi.framework.BundleException;
import org.osgi.framework.ServiceReference;

import org.papoose.core.framework.spi.BundleStore;


/**
 * @version $Revision$ $Date$
 */
class ExtensionImpl extends AbstractBundle
{
    public ExtensionImpl(long bundleId, BundleStore bundleStore, AbstractStore archiveStore)
    {
        super(bundleId, bundleStore, archiveStore);
    }

    public int getState()
    {
        return 0;  //todo: consider this autogenerated code
    }

    public void start() throws BundleException
    {
        //todo: consider this autogenerated code
    }

    public void stop() throws BundleException
    {
        //todo: consider this autogenerated code
    }

    public void update() throws BundleException
    {
        //todo: consider this autogenerated code
    }

    public void update(InputStream inputStream) throws BundleException
    {
        //todo: consider this autogenerated code
    }

    public void uninstall() throws BundleException
    {
        //todo: consider this autogenerated code
    }

    public Dictionary getHeaders()
    {
        return null;  //todo: consider this autogenerated code
    }

    public String getLocation()
    {
        return null;  //todo: consider this autogenerated code
    }

    public ServiceReference[] getRegisteredServices()
    {
        return new ServiceReference[0];  //todo: consider this autogenerated code
    }

    public ServiceReference[] getServicesInUse()
    {
        return new ServiceReference[0];  //todo: consider this autogenerated code
    }

    public boolean hasPermission(Object object)
    {
        return false;  //todo: consider this autogenerated code
    }

    public URL getResource(String string)
    {
        return null;  //todo: consider this autogenerated code
    }

    public Dictionary getHeaders(String string)
    {
        return null;  //todo: consider this autogenerated code
    }

    public String getSymbolicName()
    {
        return null;  //todo: consider this autogenerated code
    }

    public Class loadClass(String string) throws ClassNotFoundException
    {
        return null;  //todo: consider this autogenerated code
    }

    public Enumeration getResources(String string) throws IOException
    {
        return null;  //todo: consider this autogenerated code
    }

    public Enumeration getEntryPaths(String string)
    {
        return null;  //todo: consider this autogenerated code
    }

    public URL getEntry(String string)
    {
        return null;  //todo: consider this autogenerated code
    }

    public long getLastModified()
    {
        return 0;  //todo: consider this autogenerated code
    }

    public Enumeration findEntries(String string, String string1, boolean b)
    {
        return null;  //todo: consider this autogenerated code
    }
}
