/**
 *
 * Copyright 2008 (C) The original author or authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.papoose.core;

import java.security.AccessControlContext;
import java.util.Enumeration;

import org.osgi.service.condpermadmin.ConditionInfo;
import org.osgi.service.condpermadmin.ConditionalPermissionAdmin;
import org.osgi.service.condpermadmin.ConditionalPermissionInfo;
import org.osgi.service.permissionadmin.PermissionInfo;


/**
 * @version $Revision$ $Date$
 */
public class ConditionalPermissionAdminImpl implements ConditionalPermissionAdmin
{
    private final Papoose framework;

    public ConditionalPermissionAdminImpl(Papoose framework)
    {
        this.framework = framework;
    }

    public ConditionalPermissionInfo addConditionalPermissionInfo(ConditionInfo[] conditionInfos, PermissionInfo[] permissionInfos)
    {
        return null;  //todo: consider this autogenerated code
    }

    public ConditionalPermissionInfo setConditionalPermissionInfo(String s, ConditionInfo[] conditionInfos, PermissionInfo[] permissionInfos)
    {
        return null;  //todo: consider this autogenerated code
    }

    public Enumeration getConditionalPermissionInfos()
    {
        return null;  //todo: consider this autogenerated code
    }

    public ConditionalPermissionInfo getConditionalPermissionInfo(String s)
    {
        return null;  //todo: consider this autogenerated code
    }

    public AccessControlContext getAccessControlContext(String[] strings)
    {
        return null;  //todo: consider this autogenerated code
    }
}
