/**
 *
 * Copyright 2008 (C) The original author or authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.papoose.core.framework;

import java.net.URLConnection;
import java.net.URL;
import java.net.InetAddress;
import java.io.IOException;

import org.osgi.service.url.URLStreamHandlerService;
import org.osgi.service.url.URLStreamHandlerSetter;

/**
 * @version $Revision$ $Date$
 */
public class URLStreamHandlerServiceImpl implements URLStreamHandlerService
{
    public URLConnection openConnection(URL url) throws IOException
    {
        return null;  //todo: consider this autogenerated code
    }

    public void parseURL(URLStreamHandlerSetter urlStreamHandlerSetter, URL url, String s, int i, int i1)
    {
        //todo: consider this autogenerated code
    }

    public String toExternalForm(URL url)
    {
        return null;  //todo: consider this autogenerated code
    }

    public boolean equals(URL url, URL url1)
    {
        return false;  //todo: consider this autogenerated code
    }

    public int getDefaultPort()
    {
        return 0;  //todo: consider this autogenerated code
    }

    public InetAddress getHostAddress(URL url)
    {
        return null;  //todo: consider this autogenerated code
    }

    public int hashCode(URL url)
    {
        return 0;  //todo: consider this autogenerated code
    }

    public boolean hostsEqual(URL url, URL url1)
    {
        return false;  //todo: consider this autogenerated code
    }

    public boolean sameFile(URL url, URL url1)
    {
        return false;  //todo: consider this autogenerated code
    }
}
