/**
 *
 * Copyright 2008 (C) The original author or authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.papoose.core;

import org.osgi.framework.BundleContext;
import org.osgi.framework.ServiceRegistration;
import org.osgi.service.permissionadmin.PermissionAdmin;
import org.osgi.service.permissionadmin.PermissionInfo;


/**
 *
 */
public class PermissionAdminImpl implements PermissionAdmin
{
    private Papoose framework;
    private ServiceRegistration registration;

    public void start(Papoose framework)
    {
        this.framework = framework;

        BundleContext context = framework.getSystemBundleContext();

        registration = context.registerService(PermissionAdmin.class.getName(), this, null);
    }

    public void stop()
    {
        BundleContext context = framework.getSystemBundleContext();

        registration.unregister();

        registration = null;
        framework = null;
    }

    public PermissionInfo[] getPermissions(String s)
    {
        return new PermissionInfo[0];  //todo: consider this autogenerated code
    }

    public void setPermissions(String s, PermissionInfo[] permissionInfos)
    {
        //todo: consider this autogenerated code
    }

    public String[] getLocations()
    {
        return new String[0];  //todo: consider this autogenerated code
    }

    public PermissionInfo[] getDefaultPermissions()
    {
        return new PermissionInfo[0];  //todo: consider this autogenerated code
    }

    public void setDefaultPermissions(PermissionInfo[] permissionInfos)
    {
        //todo: consider this autogenerated code
    }
}
